// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// throwAndCatchInterrupt
void throwAndCatchInterrupt();
RcppExport SEXP _exceptiontest_throwAndCatchInterrupt() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    throwAndCatchInterrupt();
    return R_NilValue;
END_RCPP
}
